# Generated by Django 2.2.5 on 2019-09-09 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title', models.CharField(max_length=255)),
                ('blog_image', models.ImageField(upload_to='blogs/')),
                ('blog_pub_date', models.DateTimeField()),
                ('blog_text', models.TextField()),
            ],
        ),
    ]
