# Generated by Django 2.2.5 on 2019-09-11 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enquiry_email', models.CharField(max_length=255)),
                ('enquiry_topic', models.CharField(max_length=255)),
                ('enquiry_description', models.TextField()),
                ('enquiry_date', models.DateTimeField()),
            ],
        ),
    ]
